apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/shared-gateway
  http:
  - match:
    route:
    - destination:
        host: httpbin
        port:
          number: 8000
